# Generated by Django 4.1.1 on 2022-10-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_tbl',
            name='confirm_password',
        ),
    ]
